### ISSUE TITLE
"the format of the input string is incorrect."

### ISSUE THREAD

**Issue by MyrmeC1** [coolio986/Digital_Indicator#1]
"the format of the input string is incorrect."
There must be a source code error to separate the two columns A and B on the CSV file. 
I cannot start the filament diameter capture
[02-16-2022_ABSMED_Spool7_Batch1.csv](https://github.com/coolio986/Digital_Indicator/files/8080682/02-16-2022_ABSMED_Spool7_Batch1.csv)

**Comment by coolio986** [comment]
Can you please post the stack trace?

**Comment by coolio986** [comment]
Closed from no response
